@startuml "sequence_high_level"
actor User
participant "Hardware Controller" as HW
participant "ImGuiView" as View
participant "AppController" as Ctrl
participant "AudioPlayer" as Audio
participant "SerialManager" as Serial
participant "MediaFile" as Media
participant "PlayerState" as State
participant "Local/USB Storage" as USB


    User -> View : 1.Select Song
    activate View

    View -> Ctrl : 1.1.loadTrack(path)
    activate Ctrl

    Ctrl -> Media : 1.1.1.create(path)
    activate Media
    Media -> USB : 1.1.1.1.read metadata
    activate USB
    USB --> Media : 1.1.1.2.file data
    deactivate USB
    Media --> Ctrl : 1.1.2.return metadata
    deactivate Media
    
    Ctrl -> Audio : 1.1.3.load(path)
    activate Audio
    Audio --> Ctrl : 1.1.4.ready to play
    deactivate Audio
    
    Ctrl -> State : 1.1.5.setCurrentTrack
    activate State
    State --> Ctrl: 1.1.6.return state track
    deactivate State

    Ctrl --> View : 1.2.ready
    deactivate Ctrl
    View --> User : 2.show song is playing
    deactivate View


    ' --- Hardware Flow Scenario ---
    User -> HW : 3.Press Button
    activate HW
    HW -> Ctrl : 3.1.Data Transmission
    deactivate HW
    activate Ctrl
    Ctrl -> Serial:3.1.1.send DataCallback("PLAY")
    activate Serial
    Serial -> Serial : 3.1.1.1.parse complete command
    Serial --> Ctrl : 3.1.2.trigger DataCallback("PLAY")
    deactivate Serial
    
    Ctrl -> Ctrl : 3.1.3.processCommand()
    
    Ctrl -> Audio : 3.1.4.play()
    activate Audio
    Audio --> Ctrl : 3.1.5.playback started
    deactivate Audio
    
    Ctrl -> State : 3.1.6.setPlaybackState(PLAYING)
    activate State
    State --> Ctrl: 3.1.7.return state track
    deactivate State
    
    ' Backwards notification to HW
    Ctrl -> Serial : 3.1.8.send("STATUS:PLAYING")
    activate Serial
    Serial --> Ctrl : 3.1.9.return status
    deactivate Serial
    
    ' UI update via callback
    Ctrl --> View : 3.2.trigger StateCallback(RUNNING)
    deactivate Ctrl
    activate View
    View --> User : 4.show song is playing
    deactivate View
    
@enduml
